export const mockMealDetailsSushi = {
  meals: [
    {
      idMeal: '53065',
      strMeal: 'Sushi',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Japanese',
      strInstructions: 'STEP 1rnTO MAKE SUSHI ROLLS: ...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
      strIngredient1: 'Sushi Rice',
      strIngredient2: 'Rice wine',
      strIngredient3: 'Caster Sugar',
      strIngredient4: 'Mayonnaise',
      strIngredient5: 'Rice wine',
      strIngredient6: 'Soy Sauce',
      strIngredient7: 'Cucumber',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '300ml ',
      strMeasure2: '100ml',
      strMeasure3: '2 tbs',
      strMeasure4: '3 tbs',
      strMeasure5: '1 tbs',
      strMeasure6: '1 tbs',
      strMeasure7: '1',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.bbcgoodfood.com/recipes/simple-sushi',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
