export const mockMealsLetter = {
  meals: [
    {
      idMeal: '52776',
      strMeal: 'Chocolate Gateau',
      strCategory: 'Dessert',
      strArea: 'French',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=dsJtgmAhFF4',
    },
    {
      idMeal: '52765',
      strMeal: 'Chicken Enchilada Casserole',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Mexican',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg',
      strTags: 'Casserole,Cheasy,Meat',
      strYoutube: 'https://www.youtube.com/watch?v=EtVkwVKLc_M',
    },
    {
      idMeal: '52779',
      strMeal: 'Cream Cheese Tart',
      strDrinkAlternate: null,
      strCategory: 'Starter',
      strArea: 'Unknown',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg',
      strTags: 'Tart,Savory',
      strYoutube: 'https://www.youtube.com/watch?v=UhQPwO4uymo',
    },
    {
      idMeal: '52788',
      strMeal: 'Christmas Pudding Flapjack',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vvusxs1483907034.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=OaqvGvEiwzU',
    },
    {
      idMeal: '52795',
      strMeal: 'Chicken Handi',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Indian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=IO0issT0Rmc',
    },
    {
      idMeal: '52796',
      strMeal: 'Chicken Alfredo Primavera',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Italian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=qCIbq8HywpQ',
    },
    {
      idMeal: '52818',
      strMeal: 'Chicken Fajita Mac and Cheese',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'American',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=bwTSmLTZKNg',
    },
    {
      idMeal: '52819',
      strMeal: 'Cajun spiced fish tacos',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Mexican',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=N4EdUt0Ou48',
    },
    {
      idMeal: '52830',
      strMeal: 'Crock Pot Chicken Baked Tacos',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Mexican',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=oqL0mLDBzS4',
    },
    {
      idMeal: '52831',
      strMeal: 'Chicken Karaage',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Japanese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=XivddFddthc',
    },
    {
      idMeal: '52832',
      strMeal: 'Coq au vin',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'French',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=_ise46LADBs',
    },
    {
      idMeal: '52839',
      strMeal: 'Chilli prawn linguine',
      strDrinkAlternate: null,
      strCategory: 'Pasta',
      strArea: 'Italian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=SC17Mc70Db0',
    },
    {
      idMeal: '52840',
      strMeal: 'Clam chowder',
      strDrinkAlternate: null,
      strCategory: 'Starter',
      strArea: 'American',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/rvtvuw1511190488.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=fEN_fm6kX6k',
    },
  ],
};
