export const mockInProgressMeal = {
  meals: [
    {
      idMeal: '53026',
      strMeal: 'Tamiya',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strInstructions: 'oak the beans in water to cover overnight...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
      strIngredient1: 'Broad Beans',
      strIngredient2: 'Spring Onions',
      strIngredient3: 'Garlic Clove',
      strIngredient4: 'Parsley',
      strIngredient5: 'Cumin',
      strIngredient6: 'Baking Powder',
      strIngredient7: 'Cayenne Pepper',
      strIngredient8: 'Flour',
      strIngredient9: 'Vegetable Oil',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 cups ',
      strMeasure2: '6',
      strMeasure3: '4',
      strMeasure4: '1/4 cup',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: 'Spinkling',
      strMeasure9: 'As required',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const mockInProgressDrink = {
  drinks: [
    {
      idDrink: '17225',
      strDrink: 'Ace',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake all the ingredients in a cocktail ...',
      strInstructionsES: 'Agite todos los ingredientes en una coctelera ...',
      strInstructionsDE: 'Alle Zutaten in einem Cocktailshaker mit ...',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti ...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: 'Heavy cream',
      strIngredient4: 'Milk',
      strIngredient5: 'Egg White',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 shots ',
      strMeasure2: '1/2 shot ',
      strMeasure3: '1/2 shot ',
      strMeasure4: '1/2 shot',
      strMeasure5: '1/2 Fresh',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 22:05:06',
    },
  ],
};
