export const mockMeals = {
  meals: [
    {
      idMeal: '52977',
      strMeal: 'Corba',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
    },
    {
      idMeal: '53060',
      strMeal: 'Burek',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Croatian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
    },
    {
      idMeal: '53065',
      strMeal: 'Sushi',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Japanese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
    },
    {
      idMeal: '52978',
      strMeal: 'Kumpir',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
    },
    {
      idMeal: '53069',
      strMeal: 'Bistek',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Filipino',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=xOQON5_S7as',
    },
    {
      idMeal: '53026',
      strMeal: 'Tamiya',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
    },
    {
      idMeal: '52971',
      strMeal: 'Kafteji',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=-TFf-Zu-xQU',
    },
    {
      idMeal: '52844',
      strMeal: 'Lasagne',
      strDrinkAlternate: null,
      strCategory: 'Pasta',
      strArea: 'Italian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=gfhfsBPt46s',
    },
    {
      idMeal: '52785',
      strMeal: 'Dal fry',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Indian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
    },
    {
      idMeal: '52948',
      strMeal: 'Wontons',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Chinese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525876468.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=9h9No18ZyCI',
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
    },
    {
      idMeal: '52929',
      strMeal: 'Timbits',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
    },
    {
      idMeal: '53027',
      strMeal: 'Koshari',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/4er7mj1598733193.jpg',
      strYoutube: 'https://www.youtube.com/watch?v=y0d2ZMZBW4Y',
    },
  ],
};
